import type { CatalogProduct } from "../src/lib/pricing";
import { rupeesToPaise as r } from "../src/lib/money";

/** Seed source for Product + ProductCredit. All values are editable in Admin afterwards. */
export const PRODUCTS: CatalogProduct[] = [
  {
    slug: "call-convert-plus",
    name: "Call Convert Plus",
    kind: "BUNDLE",
    pricePaise: r(3999),
    mrpPaise: r(4999),
    mentorPricePaise: r(2999),
    enrolledOnly: false,
    withAdmin: false,
    credits: [
      { kind: "PI", quantity: 6 },
      { kind: "GD", quantity: 3 },
      { kind: "WAT", quantity: 2 },
      { kind: "SOP_DETAILED", quantity: 1 },
      { kind: "SOP_REVISION", quantity: 1 },
      { kind: "STRATEGY", quantity: 2 },
    ],
    summary: "6 PI, 3 GD, 2 WAT, SOP + revision, 2 strategy calls, deep dossier.",
    includes: [
      "6 mock PIs including institute-final rounds",
      "3 GD/GE batches",
      "2 WAT evaluations",
      "1 detailed SOP review plus one revision",
      "2 strategy calls",
      "Deep dossier per institute, multi-college prep",
    ],
    badge: "Multiple calls",
  },
  {
    slug: "call-convert",
    name: "Call Convert",
    kind: "BUNDLE",
    pricePaise: r(2599),
    mrpPaise: r(2999),
    mentorPricePaise: r(2199),
    enrolledOnly: false,
    withAdmin: false,
    credits: [
      { kind: "PI", quantity: 4 },
      { kind: "GD", quantity: 2 },
      { kind: "WAT", quantity: 1 },
      { kind: "SOP_DETAILED", quantity: 1 },
      { kind: "STRATEGY", quantity: 1 },
    ],
    summary: "4 PI, 2 GD, 1 WAT, 1 detailed SOP, 1 strategy call.",
    includes: [
      "4 mock PIs across different focus areas",
      "2 GD/GE batches",
      "1 WAT evaluation",
      "1 detailed SOP review",
      "1 strategy call with Samrudh",
      "Profile review, personalised booklet, form guidance",
    ],
    badge: "Most bought",
  },
  {
    slug: "mock-pi",
    name: "Mock PI",
    kind: "SINGLE",
    pricePaise: r(599),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "PI", quantity: 1 }],
    summary: "One hour, one focus area, written feedback in 24 hours.",
    includes: [],
  },
  {
    slug: "additional-pi",
    name: "Additional PI",
    kind: "SINGLE",
    pricePaise: r(449),
    mrpPaise: r(599),
    mentorPricePaise: null,
    enrolledOnly: true,
    withAdmin: false,
    credits: [{ kind: "PI", quantity: 1 }],
    summary: "For enrolled students who want one more.",
    includes: [],
  },
  {
    slug: "mock-gd",
    name: "Mock GD/GE",
    kind: "SINGLE",
    pricePaise: r(199),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "GD", quantity: 1 }],
    summary: "Eight-person batch, live moderation, individual notes.",
    includes: [],
  },
  {
    slug: "wat",
    name: "WAT evaluation",
    kind: "SINGLE",
    pricePaise: r(199),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "WAT", quantity: 1 }],
    summary: "Upload your essay, get it marked against the same rubric.",
    includes: [],
  },
  {
    slug: "sop-detailed",
    name: "Detailed SOP review",
    kind: "SINGLE",
    pricePaise: r(399),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "SOP_DETAILED", quantity: 1 }],
    summary: "Line edits plus a rewrite of your weakest paragraph.",
    includes: [],
  },
  {
    slug: "sop-basic",
    name: "Basic SOP review",
    kind: "SINGLE",
    pricePaise: r(99),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "SOP_BASIC", quantity: 1 }],
    summary: "Structure, tone and red flags. No line edits.",
    includes: [],
  },
  {
    slug: "quick-guidance",
    name: "Quick Guidance",
    kind: "SINGLE",
    pricePaise: r(299),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "GUIDANCE", quantity: 1 }],
    summary: "A 45-minute call on what to prioritise before your date.",
    includes: [],
  },
  {
    slug: "pi-with-samrudh",
    name: "PI with Samrudh",
    kind: "SINGLE",
    pricePaise: r(699),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: true,
    earlyBird: { pricePaise: r(599), limit: 10, seatsLeft: 10 },
    credits: [{ kind: "PI_DIRECT", quantity: 1 }],
    summary: "A full one-hour mock interview, directly with Samrudh.",
    includes: ["1 hour, one-to-one with Samrudh", "Written feedback within 24 hours"],
    badge: "With Samrudh",
  },
  {
    slug: "strategy-with-samrudh",
    name: "Strategy call with Samrudh",
    kind: "SINGLE",
    pricePaise: r(349),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: true,
    earlyBird: { pricePaise: r(299), limit: 10, seatsLeft: 10 },
    credits: [{ kind: "STRATEGY_DIRECT", quantity: 1 }],
    summary: "30 minutes with Samrudh on which calls to prioritise and how to position your profile.",
    includes: ["30 minutes, one-to-one with Samrudh"],
    badge: "With Samrudh",
  },
  {
    slug: "panel-pi",
    name: "Panel PI",
    kind: "SINGLE",
    pricePaise: r(999),
    mrpPaise: r(1499),
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: false,
    credits: [{ kind: "PANEL_PI", quantity: 1 }],
    summary: "Three panelists, one hour. The closest thing to the real interview.",
    includes: ["Three interviewers on one panel, as in the real thing", "One hour in total, interview and live debrief", "One combined feedback report afterwards"],
    badge: "Closest to live",
  },
  {
    slug: "panel-pi-upgrade",
    name: "Panel PI upgrade",
    kind: "SINGLE",
    pricePaise: r(199),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: true,
    withAdmin: false,
    credits: [],
    summary: "Turn one of your unused mock PIs into a Panel PI. For Call Convert Plus students, up to two.",
    includes: ["Swaps one unused mock PI for one Panel PI", "Up to 2 of your 6 PIs"],
    badge: "Plus students",
  },
  {
    slug: "trial-guidance",
    name: "Trial guidance call",
    kind: "SINGLE",
    pricePaise: r(10),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: true,
    credits: [{ kind: "TRIAL_GUIDANCE", quantity: 1 }],
    summary: "A 25-minute guidance call with Samrudh, for \u20b910. Same quality as the full sessions.",
    includes: ["25 minutes, one-to-one with Samrudh", "An honest read on where you stand"],
    badge: "Trial",
  },
  {
    slug: "trial-mock-pi",
    name: "Trial mock PI",
    kind: "SINGLE",
    pricePaise: r(50),
    mrpPaise: null,
    mentorPricePaise: null,
    enrolledOnly: false,
    withAdmin: true,
    credits: [{ kind: "TRIAL_PI", quantity: 1 }],
    summary: "A real mock PI with Samrudh, for \u20b950. Same quality as the full sessions.",
    includes: ["A real mock PI, one-to-one with Samrudh", "Written feedback within 24 hours"],
    badge: "Trial",
  },
];

/** Display order of the single-service grid on /packages. */
export const SINGLES_ORDER = [
  "mock-pi",
  "additional-pi",
  "mock-gd",
  "wat",
  "sop-basic",
  "sop-detailed",
  "quick-guidance",
  "pi-with-samrudh",
  "strategy-with-samrudh",
  "panel-pi",
];
