import type { CatalogProduct } from "../src/lib/pricing";
import { rupeesToPaise as r } from "../src/lib/money";

/** Seed source for Product + ProductCredit. All values are editable in Admin afterwards. */
// 31 January 2027, end of day IST.
export const EARLY_BIRD_END = new Date("2027-01-31T23:59:59+05:30");

export const PRODUCTS: CatalogProduct[] = [
  {
    slug: "call-convert-plus",
    name: "Call Convert Plus",
    kind: "BUNDLE",
    pricePaise: r(2999),
    mrpPaise: r(4999),
    earlyBirdEndsAt: EARLY_BIRD_END,
    enrolledOnly: false,
    credits: [
      { kind: "PI", quantity: 6 },
      { kind: "GD", quantity: 3 },
      { kind: "WAT", quantity: 2 },
      { kind: "SOP_DETAILED", quantity: 1 },
      { kind: "SOP_REVISION", quantity: 1 },
      { kind: "STRATEGY", quantity: 2 },
    ],
    summary: "6 PI, 3 GD, 2 WAT, SOP + revision, 2 strategy calls, deep dossier.",
    includes: [
      "6 mock PIs including institute-final rounds",
      "3 GD/GE batches",
      "2 WAT evaluations",
      "1 detailed SOP review plus one revision",
      "2 strategy calls",
      "Deep dossier per institute, multi-college prep",
    ],
    badge: "Multiple calls",
  },
  {
    slug: "call-convert",
    name: "Call Convert",
    kind: "BUNDLE",
    pricePaise: r(2199),
    mrpPaise: r(2999),
    earlyBirdEndsAt: EARLY_BIRD_END,
    enrolledOnly: false,
    credits: [
      { kind: "PI", quantity: 4 },
      { kind: "GD", quantity: 2 },
      { kind: "WAT", quantity: 1 },
      { kind: "SOP_DETAILED", quantity: 1 },
      { kind: "STRATEGY", quantity: 1 },
    ],
    summary: "4 PI, 2 GD, 1 WAT, 1 detailed SOP, 1 strategy call.",
    includes: [
      "4 mock PIs across different focus areas",
      "2 GD/GE batches",
      "1 WAT evaluation",
      "1 detailed SOP review",
      "1 strategy call with Samrudh",
      "Profile review, personalised booklet, form guidance",
    ],
    badge: "Most bought",
  },
  {
    slug: "mock-pi",
    name: "Mock PI",
    kind: "SINGLE",
    pricePaise: r(599),
    mrpPaise: null,
    earlyBirdEndsAt: null,
    enrolledOnly: false,
    credits: [{ kind: "PI", quantity: 1 }],
    summary: "One hour, one focus area, written feedback in 24 hours.",
    includes: [],
  },
  {
    slug: "additional-pi",
    name: "Additional PI",
    kind: "SINGLE",
    pricePaise: r(449),
    mrpPaise: r(599),
    earlyBirdEndsAt: null,
    enrolledOnly: true,
    credits: [{ kind: "PI", quantity: 1 }],
    summary: "For enrolled students who want one more.",
    includes: [],
  },
  {
    slug: "mock-gd",
    name: "Mock GD/GE",
    kind: "SINGLE",
    pricePaise: r(199),
    mrpPaise: null,
    earlyBirdEndsAt: null,
    enrolledOnly: false,
    credits: [{ kind: "GD", quantity: 1 }],
    summary: "Eight-person batch, live moderation, individual notes.",
    includes: [],
  },
  {
    slug: "wat",
    name: "WAT evaluation",
    kind: "SINGLE",
    pricePaise: r(199),
    mrpPaise: null,
    earlyBirdEndsAt: null,
    enrolledOnly: false,
    credits: [{ kind: "WAT", quantity: 1 }],
    summary: "Upload your essay, get it marked against the same rubric.",
    includes: [],
  },
  {
    slug: "sop-detailed",
    name: "Detailed SOP review",
    kind: "SINGLE",
    pricePaise: r(399),
    mrpPaise: null,
    earlyBirdEndsAt: null,
    enrolledOnly: false,
    credits: [{ kind: "SOP_DETAILED", quantity: 1 }],
    summary: "Line edits plus a rewrite of your weakest paragraph.",
    includes: [],
  },
  {
    slug: "sop-basic",
    name: "Basic SOP review",
    kind: "SINGLE",
    pricePaise: r(99),
    mrpPaise: null,
    earlyBirdEndsAt: null,
    enrolledOnly: false,
    credits: [{ kind: "SOP_BASIC", quantity: 1 }],
    summary: "Structure, tone and red flags. No line edits.",
    includes: [],
  },
  {
    slug: "quick-guidance",
    name: "Quick Guidance",
    kind: "SINGLE",
    pricePaise: r(299),
    mrpPaise: null,
    earlyBirdEndsAt: null,
    enrolledOnly: false,
    credits: [{ kind: "GUIDANCE", quantity: 1 }],
    summary: "A 45-minute call on what to prioritise before your date.",
    includes: [],
  },
];

/** Display order of the single-service grid on /packages. */
export const SINGLES_ORDER = [
  "mock-pi",
  "additional-pi",
  "mock-gd",
  "wat",
  "sop-basic",
  "sop-detailed",
  "quick-guidance",
];

